server.port=${SERVER_PORT:8085}
server.servlet.context-path=/

logging.level.root=info
logging.level.com.ssafy.live=debug

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
