server.port=${SERVER_PORT:8081}
server.servlet.context-path=/

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://127.0.0.1:3306/homedb?serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

mybatis.mapper-locations=mapper/*.xml
mybatis.type-aliases-package=com.ssafy.live.user.dto

logging.level.root=info
logging.level.com.ssafy.live=debug

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
